### ISSUE TITLE
Bug in interval definition version 2.20.1 on fdroid

### ISSUE THREAD

**Issue by Ulrichgau** [mkulesh/microMathematics#105]
Hello Mikhail
There is a bug in the interval definition:
It works only correctly with lower interval limit = 0. 
On positive lower limits there is no Interval generated
On negative lower limits, the step is "-lowerLimit + step"
So for example
x:= [-2,0.01..10] leads to x0 = -2, x1 = 0.01, x2 = 2.02 and so on.
Best regards
Uli

**Comment by mkulesh** [comment]
Hi @Ulrichgau,
thank you for issue. I am not able to reproduce it with the latest version 2.21. From my point of view everything works as desired:
![Screenshot_20201222-204635](https://user-images.githubusercontent.com/30557348/102927288-f6b87900-4496-11eb-82fe-b964aeeb5cfd.png)

Could you please try the latest release https://github.com/mkulesh/microMathematics/releases/download/v2.21.0/microMathematics-v2.21.0.apk that shall also appear on F-Droid soon. Are you able to reproduce the problem in this build?

**Comment by mkulesh** [comment]
Closed since there is no response.
