### ISSUE TITLE
Screenshots for F-Droid 

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [mkulesh/microMathematics#106]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by mkulesh** [comment]
Hi @mondlicht-und-sterne 
thank you for the info. I will do it for the next release.

**Comment by mondlicht-und-sterne** [comment]
thank you that would be great

**Comment by mkulesh** [comment]
Hi @mondlicht-und-sterne 
new app description with screenshots is now available on F-Droid: https://f-droid.org/packages/com.mkulesh.micromath.plus/
I think I can now close the issue.
