### ISSUE TITLE
input E numbers

### ISSUE THREAD

**Issue by tino1003870** [mkulesh/microMathematics#110]
Hi,

entering values like "1.6E-6 J" leads to a state where the negative exponent is parsed as a regular "-" operand. Bad for calculations with physical values.

**Comment by mkulesh** [comment]
Hi @tino1003870 
I am now preparing a new release, where this issue is fixed. Do you like to test the fix before the app will be released?

**Comment by tino1003870** [comment]
Hi Mikhail,

I think it is too late, right? If there is still a chance, testing would be
a good idea.

Best,

Tino

Am Fr., 2. Sept. 2022 um 20:05 Uhr schrieb Mikhail Kulesh <
***@***.***>:

**Comment by mkulesh** [comment]
Hi @tino1003870,
I already submitted the release to the Google Play, but it is not yet accepted by Google. The test build is available here: https://1drv.ms/u/s!At2sh2-YDyGFgSG0SHVv53EhBSTQ?e=96HGWB
Do E numbers now work as desired for you in this build?

**Comment by tino1003870** [comment]
Hi Mikhal,

Installed this prerelease. Opening an old calculation, the existing E
numbers appeared to showup with xxx*1E-yyy, which is correct.
Entering "test:=1e-6" worked, it stayed as it was entered even after
closing the app (forced) and reopening.
After reopening I loaded a different file. Opening the attached open again,
test stayed as entered. Works too.

Thank you for incorporating this feature.

Best,

Tino


Mikhail Kulesh ***@***.***> schrieb am Mo., 5. Sept. 2022,
22:01:

**Comment by mkulesh** [comment]
Hi @tino1003870 
thank you for feedback! Unfortunately Google rejected my submission since I used "manage external storage" permission that is not allowed anymore for a such kind of apps. I shall remove now any direct access to the external storage and only keep the Storage Access Framework (Android Documents feature) for the document management. This change will take some time into account.

**Comment by tino1003870** [comment]
Hi Mikhail,

please check the attached mmt.
Calculation with e-numbers is okay, but the diagram not.
Any idea why?

Best,
Tino

Mikhail Kulesh ***@***.***> schrieb am Do., 8. Sept. 2022,
22:45:

**Comment by tino1003870** [comment]
Mmt ... please ignore. Diagram works too ... my fault in "lambda"-array.

Mikhail Kulesh ***@***.***> schrieb am Do., 8. Sept. 2022,
22:45:

**Comment by mkulesh** [comment]
Released in version 2.22.1
Merged into free branch
