### ISSUE TITLE
Update documentation for new matrix defintion

### ISSUE THREAD

**Issue by yashpalgoyal1304** [mkulesh/microMathematics#112]
Complementary to https://github.com/mkulesh/microMathematics/issues/108

**Comment by yashpalgoyal1304** [comment]
i'd like to work on this with some assistance, guidance and feedback

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304,
the simplest way just get the latest PDF (https://github.com/mkulesh/microMathematics/blob/supplement/doc/microMathematics-v2.22.0.pdf), and send me a text document that contain changes with respect to this PDF. I will than include it into the App documentation and generate new PDFs. Alternatively, if you have LaTeX installed, just expand the file https://github.com/mkulesh/microMathematics/blob/master/doc/how_to_use.tex and attach it here (do not open a pull request since this file is auto-generated). I will than merge these changes into the app documentation.

**Comment by yashpalgoyal1304** [comment]
Pasting the link for my own reference

https://docs.google.com/viewer?url=https://github.com/mkulesh/microMathematics/raw/supplement/doc/microMathematics-v2.22.0.pdf

**Comment by yashpalgoyal1304** [comment]
Github is not allowing uploading .tex files.

![image](https://user-images.githubusercontent.com/19423063/162637490-1270da4c-12bd-4d7c-a972-87195b5aca6d.png)


So, i'll open that pull request as a medium to share the .tex file.

I hope it's ohkay with you :innocent:

| | Original | Suggestion |
-- | -- | --
.pdf | [original][mm-o-p] | [suggestion-rendered][mm-s-p]
.tex | [original][mm-o-t] | [suggestion-source][mm-s-t]

[mm-o-p]: https://docs.google.com/viewer?url=https://github.com/mkulesh/microMathematics/blob/supplement/doc/microMathematics-v2.22.0.pdf
[mm-s-p]: https://docs.google.com/viewer?url=https://github.com/mkulesh/microMathematics/files/8459774/microMathematics.pdf
[mm-o-t]: https://github.com/mkulesh/microMathematics/blob/3bc2434c827a2c43080d6d566847ef2c2a15aa96/doc/how_to_use.tex
[mm-s-t]: https://www.example.com

**Comment by yashpalgoyal1304** [comment]
here's the place where you can see the .tex file i made:

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304,
thank you for providing the updates. I will merge it within the next couple of days...

**Comment by yashpalgoyal1304** [comment]
Though i think the suggestions should be good, but be sure to check these
for aptness and errors from your side them as well. :innocent:

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304,
I successfully merged your updates and applied some minor changes. Please note that from the technical reason I shall have the same order of images across all translations, therefore I reverted one update related to the image order change. Could you please build the app and pdf and review whether the changes in build-in app documentation and pdf are as desired?

**Comment by yashpalgoyal1304** [comment]
Hey!

* Building the pdf: yeah, i will do that.
* Building app: I dont have much xp, but i will try.
* Though i will try building app, but asking for curiousity, will it
suffice if rather than building app, I just open the new .mmt file in the
existing app?

Mikhail Kulesh wrote:

> Could you please build the app and pdf and review whether the changes in
> build-in app documentation and pdf are as desired?
>

**Comment by mkulesh** [comment]
Hi, I also uploaded the APK here:
https://github.com/mkulesh/microMathematics/raw/autobuild/autobuild/microMathematics-v2.22.0-release.apk

You can just download and install it. Depending on the store where you installed the actual version, you may need to uninstall it before this new build can be installed.

You do not need to open any .mm file, just select "How To Use" from the navigation menu and new text shall appear.

In order to build the app manually, you need Android Studio installed, please take a look on this document:
https://android-doc.github.io/sdk/installing/index.html?pkg=studio

After Android Studio is installed, you can just open the project, build it, and install either in an emulator, or on your phone. Before it, please ensure that the developer mode is activated on your phone: https://developer.android.com/studio/debug/dev-options

**Comment by yashpalgoyal1304** [comment]
yes, 3 things require attention

> r[0 := 5    r[3 := 6    r[2,0 := -4

1. This is kinda illegal. The first two equations with 1D index are not
taking affect, and rightly so, since as per the following third equation, r
is a 2D array.

> This document is also delivered with the app and stored in "Resources of
microMathematics Plus".

2. Where can those documents (units_overview.mmt , functions_overview.mmt)
be found from within app?

3. Related question to the second: On first running the app, a guiding
document opens up. Where can that be found from within app if user wants to
re-read that as a short refresher.

Mikhail Kulesh wrote:

> Could you please build the app and pdf and review whether the changes in
> build-in app documentation and pdf are as desired?
>

**Comment by yashpalgoyal1304** [comment]
oh wait, i re-tested. and it is legal. The element r[ _ ] is different from
r[ _ , _ ]. Both are executing and giving expected values.

Earlier, I thought they would conflict with each other, and confirmation
bias made me test it only with 2 arguments.

Yash wrote:

> > r[0 := 5    r[3 := 6    r[2,0 := -4
>
> 1. This is kinda illegal. The first two equations with 1D index are not
> taking affect, and rightly so, since as per the following third equation, r
> is a 2D array.
>

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304,

please feel free to update the example formula if you mean my variant is not consistent. units_overview.mmt and functions_overview.mmt stored in the resources of the app: app menu -> Open file -> Home Button -> Resources of "microMathematics": 
![Screenshot-20220416113805-782x1360](https://user-images.githubusercontent.com/30557348/163670066-722b1acc-8168-45f0-8089-af1ca17056e1.png)

The same case is the "welcome" document that is shown on the first run of the app. It is also placed in the resources of the app, but in the language-dependent sub-directory, for example doc_en for English. The file name is "welcome.mmt". Other files are  the items (documents) presented in the app navigation menu.

If you have any changes, please open the pull request with updated .tex file as before.

**Comment by mkulesh** [comment]
Scheduled for release 2.22.1

**Comment by mkulesh** [comment]
Released in version 2.22.1

**Comment by yashpalgoyal1304** [comment]
yes, 3 things require attention

> r[0 := 5    r[3 := 6    r[2,0 := -4

1. This is kinda illegal. The first two equations with 1D index are not
taking affect, and rightly so, since as per the following third equation, r
is a 2D array.

> This document is also delivered with the app and stored in "Resources of
microMathematics Plus".

2. Where can those documents (units_overview.mmt , functions_overview.mmt)
be found from within app?

3. Related question to the second: On first running the app, a guiding
document opens up. Where can that be found from within app if user wants to
re-read that as a short refresher.

Mikhail Kulesh wrote:

> Could you please build the app and pdf and review whether the changes in
> build-in app documentation and pdf are as desired?
>

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304,

you are right,  r[0 := 5    r[3 := 6    r[2,0 := -4 is a little bit confusing. I see two options:
1. I can just correct the documentation (do not mix one- and two-dimensional arrays in the same variable), but keep this functionality in the code
2. I also can include a check, that the mix one- and two-dimensional arrays in the same variable is not allowed.

That option is the best from your point of view?

The units_overview.mmt and functions_overview.mmt are stored in the "Resources of microMathematics Plus". To navigate, open app menu, than menu "Open", that press Home button in the file selection dialog, and, finally, select "Resources of microMathematics Plus". You will see units_overview.mmt, functions_overview.mmt and other documents. If you than selects a language, for example "doc_en", you will also find "welcome.mmt" document that is a a guiding document when the app is started the first time.

**Comment by yashpalgoyal1304** [comment]
* I did not send any reply via email 5 days ago whatsoever
* this above comment is a duplicate of one of my previous comment.
* see
https://github.com/florisboard/florisboard/issues/1882#issuecomment-1274881164
too where the same thing happened
* i don't know what is happening
* please help me stop this :cry:

**Comment by yashpalgoyal1304** [comment]
as for the main topic question at hand:

> 1. I can just correct the documentation (do not mix one- and two-dimensional arrays in the same variable), but keep this functionality in the code

this one seems better imo, as i don't understand the matter in proper depth have not much experience with it

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304, 
I also have no idea why some your messages are duplicated. I fixed the documentation: do not mix one- and two-dimensional arrays in the same variable. Now it looks like this:
![new_matrix](https://user-images.githubusercontent.com/30557348/196245664-0fc39241-a3af-4311-a90c-648597584b3c.png)

If you like to test the latest development build, please manually download and install this APK: https://1drv.ms/u/s!At2sh2-YDyGFgSS5KwhWlWDZD4LS?e=tBD0u4

**Comment by yashpalgoyal1304** [comment]
hi! i couldn't spot any such notice for "do not mix" in documentation: neither in above screenshot, nor in the commit. can u recheck??

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304 
with "do not mix" in documentation I mean do not demonstrate any examples that use one- and two-dimensional indices for the same variable. In new example, r1 is one-dimensional variable and r2 is two-dimensional. If you think we shall explicit write that the user shall not use mixed indices in their own worksheets, please fell free to update https://github.com/mkulesh/microMathematics/blob/master/doc/how_to_use.tex accordingly and I will merge these changes into the internal documentation.
