### ISSUE TITLE
Contrasted Text?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [mkulesh/microMathematics#114]
any thoughts about having text to be having slightly different bg than the equations.

it may create additional burden for theming - and without having much gain. so, i am just thinking out loud and want to hear what you and other people think

reference: theming of .ipynb files in vscodium and on google's online editor

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304,
thank you for the issue. There is no problem either improve the existing themes or add a new theme. You can find all available themes here: https://github.com/mkulesh/microMathematics/tree/master/app/src/main/res/values, files with name theme_*.xml.
If you have Android Studio installed, please feel free to play with these themes. If you will find a new theme, just open a pull request with a new theme_*.xml file, I will merge it and include into the app.

**Comment by mkulesh** [comment]
Hi @yashpalgoyal1304 
If you have any idea for a new color scheme, you can make a design in any graphical editor (better in Inkskape on order to be able directly access the colors of the objects) and I can add a new color theme based on this design.

**Comment by yashpalgoyal1304** [comment]
hi! thanks for the offer, but i closed this as i thought that i won't be able to work on it.
