### ISSUE TITLE
When the system language is Persian, axes boundaries filled by Persian numbers

### ISSUE THREAD

**Issue by mskf1383** [mkulesh/microMathematics#131]
If system language be RTL (Like Persian or Arabic), graphs not shown or shown incomplete:

![Screenshot_۲۰۲۳۰۲۱۰-۲۰۴۵۰۰](https://user-images.githubusercontent.com/50908329/218155094-f9a1cf62-d72e-40f0-8642-ce3cf62999c0.png)

**Comment by mskf1383** [comment]
I found the problem. When axes boundaries calculated automaticly, because the system language is Persian, it filled by Persian numbers. So MicroMathematics can't understand it and unable to plot.

**Comment by mkulesh** [comment]
Hi @mskf1383, thank you for the analysis, but Persian is not supported by the app.
