### ISSUE TITLE
Provide 'nightly' APK builds

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#17]
Could you provide 'nightly' builds regullary? Maybe, for each git commit?
* https://github.com/mkulesh/microMathematics/tree/master/release

**Comment by mkulesh** [comment]
Just a note for me self: http://www.ingloriousmind.com/blog/automated-builds-for-your-projects-on-github

**Comment by Symbian9** [comment]
@mkulesh, also look on this
* http://github.com/probonopd/uploadtool

REFERENCE:
* https://docs.travis-ci.com/user/deployment/releases/
* https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/

**Comment by Symbian9** [comment]
More info on auto build APK with Travis CI
* https://docs.travis-ci.com/user/languages/android/
* https://stackoverflow.com/questions/36139603/travis-ci-build-signed-apk-file
* http://szagurskii.com/blog/how-to-deploy-apk-to-github-releases-with-travis-ci/
* https://medium.com/@imkiran/build-a-signed-meteor-android-app-on-travis-ci-and-push-it-to-github-releases-d39c66eada6c
* https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

**Comment by mkulesh** [comment]
Travis has currently a workflow that is aimed to automatically build the github repo and automatically publish a release when a *new tag is created in github*: https://docs.travis-ci.com/user/deployment/releases

Actually, it is not that we wont since github releases are currently used to trigger *automatic FDroid builds* and we do not want to corrupt this FDroid workflow.
Thus, I do not agree to publish any github releases automatically based on commits since it is dangerous for FDroid. Only way I see at the moment is to push APK file from Travis to github master repo (into the new autobuild directory) using some git tricks (like in https://gist.github.com/willprice/e07efd73fb7f13f917ea).

I am not too familiar with git. Therefore, I shall talk with my colleagues who known it better. It will take some time, I still working on this issue.

**Comment by Symbian9** [comment]
> I am not too familiar with git. Therefore, I shall talk with my colleagues who known it better. It will take some time, I still working on this issue.

@probonopd, could you little help with it?

* https://github.com/mkulesh/microMathematics/issues/17#issuecomment-328301986

**Comment by probonopd** [comment]
@Symbian9 with what exactly?

> Thus, I do not agree to publish any github releases automatically based on commits 

What are you trying to accomplish then?

**Comment by Symbian9** [comment]
> Symbian9 with what exactly?

For solve this
> Actually, it is not that we wont since github releases are currently used to trigger automatic FDroid builds and we do not want to corrupt this FDroid workflow

@probonopd, is there a way setup Travis-CI using additional branch, but where build script (`.travis.yml`) will use sources from `master`? That will help keep unchanged F-Droid functionality in `master.

> Thus, I do not agree to publish any github releases automatically based on commits

@mkulesh, *I mean about autobuild 'nightly' for testers*; **normal users will never use 'nightly', because them will use only builds from F-Droid or PlayMarket, that always include only releases**

**Comment by mkulesh** [comment]
Hi @Symbian9, @probonopd. Sorry, I formulated it no too good.

The standard use case of the Travis CI - automatically build a release if a new tag is created in the github. If I tag something in github, both FDroid and Travis CI are triggered, but Travis has a framework that allows us to attach created APK back to the github tag. In other word, if I create a tag in github without manually build APK, than Travis is triggered; it can build a signed (i.e. for Google Play) APK and attach it to the github release related to this tag. As you see, this mechanism can not be used for 'nightly' (or commit-triggered) builds.

For 'nightly' builds (I call it autobuild triggered after any commits except a tag creation), there is following way:
- create and checkin an empty directory trubk/autobuild. Empty means that this directory contains only README.md, but not any APK.
- After any commits,  Travis CI is actually triggered and creates an APK placed on Travis virtual machine in the directory app/build/outputs/apk, see file https://github.com/mkulesh/microMathematics/blob/master/.travis.yml, section 
```
after_success:
    # Show apk
    - ls -l app/build/outputs/apk
``` 
So, I need some push.sh script, this is placed in `https://github.com/mkulesh/microMathematics/blob/master`. This script will be called in `after_success` section:
```
after_success:
    # Show and puch apk
    - ls -l app/build/outputs/apk
    - chmod +x push.sh
    - ./push.sh
``` 
This script shall add and commit the file `app/build/outputs/apk/microMathematics-v2.15.4a.apk` to the `https://github.com/mkulesh/microMathematics/blob/master/autotest` directory using github authtoken. In other word, this script shall push *only one file* in the *given place of the remote repository*.
I will be happy for any help related to such a script.

**Comment by Symbian9** [comment]
> If I tag something in github, both FDroid and Travis CI are triggered

No, you always can fully customize what Travis CI should build for what tags
* https://docs.travis-ci.com/user/customizing-the-build
* https://docs.travis-ci.com/user/environment-variables/
* https://github.com/travis-ci/travis-config
* ...
* https://stackoverflow.com/questions/28217556/travis-ci-auto-tag-build-for-github-release

**Comment by mkulesh** [comment]
Dear @Symbian9,
the main page of the repository contains now a new shield "APK autobuild" that is a direct link to the unsigned debug APK. The APK itself is placed in the directory `autobuild`. This directory also contains the helper script that pushes this APK from travis to the repository. I noticed a side effect: since this is an unsigned debug APK where the version number still be unchanged, you possible need to manually remove the previously installed version before installing a new one (I observed this effect on Xiaomi Redmi Note 4). Is this solution OK?

**Comment by Symbian9** [comment]
> Is this solution OK?

Yeah, now 'unstable' is what I mean.

(temporary this issue closed)

**Comment by Symbian9** [comment]
> Is this solution OK?

@mkulesh, Yeah, now 'unstable' produced as expected.

(temporary this issue closed)

**Comment by Symbian9** [comment]
I think that uploading 'nightly' APK directly in `master` now look like little wired.

@mkulesh, what about uploading this APK in separate branch (for example named as `nigtly-apk`), that should include only resulted APK file?

Could you setup `.travic.yml` for upload APK in separate branch?

**Comment by mkulesh** [comment]
Hi @Symbian9 , thank you for the idea, I can do it within the next couple of days.

**Comment by mkulesh** [comment]
Hi @Symbian9, the build procedure is changed. Look at https://github.com/mkulesh/microMathematics/blob/master/autobuild/README.md where I described this new procedure. Do you know any other repositories that implement the same method for snapshots deployments? If not, may be this method is new and can be a topic for an article for habrahabr. That do you think about it?

**Comment by Symbian9** [comment]
> Do you know any other repositories that implement the same method for snapshots deployments?

I don't know is similar way already used, but will try setup this for my repo too ;-)
* https://github.com/symbian9/azpainter
* (will try do it for some other of my repo too)

@probonopd, what you think about this method?

> If not, may be this method is new and can be a topic for an article for habrahabr. That do you think about it?

@mkulesh, writing a "User Guide" for this functionality (on Habrahabr, LOR, etc.) would be helpfull and I would be happy to read it! So, don't forget post a link to those articles in this issue, when you would publish them.
