### ISSUE TITLE
Add the app into F-Droid

### ISSUE THREAD

**Issue by KOLANICH** [mkulesh/microMathematics#2]
https://f-droid.org/wiki/page/FAQ_-_App_Developers#How_do_I_get_my_app_included.3F

**Comment by mkulesh** [comment]
I already submitted this app for F-Droid, see https://gitlab.com/fdroid/rfp/issues/278

**Comment by Symbian9** [comment]
Page broken in repositary view...

* https://f-droid.org/packages/com.mkulesh.micromath.plus/

..but in F-Droid client app shown ...

![app in F-Droid client](http://hnng.moe/f/TTE)

...and direct links work ...

* https://f-droid.org/repo/com.mkulesh.micromath.plus_300.apk
* https://f-droid.org/repo/com.mkulesh.micromath.plus_300_src.tar.gz
* https://f-droid.org/repo/com.mkulesh.micromath.plus_300.apk.asc

I try register account on F-Droid wiki...

* https://f-droid.org/register/

... but this page broken too. :-(

**Comment by mkulesh** [comment]
I forwarded this issue to the F-Droid team:
https://gitlab.com/fdroid/fdroiddata/issues/844

**Comment by KOLANICH** [comment]
P.S. it's not the world first scientific calculator on Android. Jupyter Notebook (so python, you can also plug octave there) works fine on Android. Mathics (and other ones working in browser) should also work fine, but I have not tried.

**Comment by mkulesh** [comment]
Hi @KOLANICH, of course, it's not the world first scientific calculator on Android. My sentence was:
"It is the world’s first scientific graphing calculator and function plotter on Android oriented around a worksheet." Important is "oriented around a worksheet", since such systems like Matcad or SMath Studio are not yet ported on Android.

**Comment by KOLANICH** [comment]
I meant that Jupyter Notebook and Mathics are also oriented around worksheet. In jypyter it is called "notebook".

**Comment by mkulesh** [comment]
OK, thank you, I will take a look on these tools and change the app description

**Comment by mkulesh** [comment]
Dear @KOLANICH. The link to the F-Droid repository is now alive; I fixed the description (removed sentence about world first calculator from description on github), it will take some time to propagate this description change to all other repositories. If everything is OK, please close the issue.

**Comment by KOLANICH** [comment]
Thank you.
