### ISSUE TITLE
F-Droid badge icon broken

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#21]
Its look like link to badge on F-Droid website not work propperly
* https://f-droid.org/badge/get-it-on.png

I propose (temporary) use icon from F-Droid repo on Gitlab
* https://gitlab.com/fdroid/artwork/raw/master/badge/get-it-on.png

Fix it in `README.md`
* https://github.com/mkulesh/microMathematics/blob/master/README.md

REFERENCE:
* https://gitlab.com/fdroid/artwork/tree/master/badge
* https://f-droid.org/2016/05/29/get-it-on-f-droid-badges.html

**Comment by mkulesh** [comment]
Fixed (used icon from F-Droid repo on Gitlab), please test and close the issue if it is OK
