### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/microMathematics#23]

**Comment by mkulesh** [comment]
See also:
- https://github.com/mkulesh/microMathematics/pull/9
- https://github.com/mkulesh/microMathematics/pull/22

**Comment by RyDroid** [comment]
I just saw that you moved the file in https://github.com/mkulesh/microMathematics/commit/b209bbc789b18cc162e1e3f83486b3b682796510. It would have been useful to keep the directory and put a README plain text file or something similar to know the move. I thought that you have completely deleted it and someone could have thought that no start of (French) translation has never existed.

**Comment by RyDroid** [comment]
Just to be sure, when the word "array", it is for a table (like `Object[]` in Java) and not for a collection (like `Collection<Object>` in Java), is not it?

**Comment by mkulesh** [comment]
Hi @RyDroid, I am really sorry that I shall move unfinished translation file into other directory. The reason is that any unfinished translation generates a lot of lint warnings that makes lint analyzer almost unusable. 

- Unfortunately, your idea to create a README plain text file in the resource directory will not work since it produces a build error, see https://travis-ci.org/mkulesh/microMathematics/builds/299529654
"/home/travis/build/mkulesh/microMathematics/app/src/main/res/values-fr/README.txt:1:1: Error: Content is not allowed in prolog.". Thus, we need an other idea to indicate the place of unfinished translation file.

- In the documentation, I have no difference between "array" aka Java[] and "array" aka collection since it is an implementation details that is not important for the end user. I tried to always use the word "array" in whole documentation if I talk about lists, collections, arrays etc..

- error_invalid_argument: "Function argument shall contain letters or digits only". It has exactly the same meaning like Java Java.lang.Character.isLetterOrDigit() method, see
https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isLetterOrDigit(char) - "Determines if the specified character is a letter or digit". May be I translated it in English wrong... If yes, please correct it

**Comment by mkulesh** [comment]
No activities
