### ISSUE TITLE
Use app name "microMathematics Plus" ("μMath+" for short) in all languages/locales

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#4]
Please, don't use translated name of app (like "Микро-математика плюс" in Russian) in any documentation or posts as official name.

Instead always use Latin character name "**microMathematics Plus**" as official app name in all locales and in official docs for all languages (official names of program should be like a brand, for example *LibreOffice Math*, *wxMaxima*, etc.)

Also, for menu entry as sign under app icon use short name "**μMath+**", because original name is too long for menu entry.

> **Micro-** (symbol **μ** ) is a unit prefix in the metric system
* https://en.wikipedia.org/wiki/Micro-

> Mathematics is commonly called Math in the US and Maths in the UK.
* https://www.mathsisfun.com

> **Mathematics** (from Greek μάθημα *máthēma*, "knowledge, study, learning"; often shortened to maths and math)
* https://en.wikipedia.org/wiki/Mathematics

> The **plus and minus** signs ( **+** and **−** ) are mathematical symbols used to represent the notions of positive and negative as well as the operations of addition and
subtraction. Their use has been extended to many other meanings, more or less analogous. *Plus* and *minus* are Latin terms meaning "more" and "less", respectively.
* https://en.wikipedia.org/wiki/%2B

**Comment by Symbian9** [comment]
@mkilesh, there is issue in the docs when name of app placed at line start `micro Mathematics Plus` transformed by you into `Micro Mathematics Plus` - its look little incorrect if this is the name of brand.

Maybe, would be better use `microMathematics` as single word (like `microphone`), also this repositary already named in such manner

* github.com/mkulesh/microMathematics

And for app name should consist from two words: `microMathematics Plus` (or `μMath+` for short)

**Comment by Poussinou** [comment]
I'm currently trying to translate the app in French, it's not that easy... You should maybe open an Issue for this kind of work, or provide some documentation, or use something like transifex or similar ;)

**Comment by mkulesh** [comment]
Dear Poussinou, please feel free to create a separate issue for this task. I think translation into French will take some time since there is a lot of documentation in the directory asset/doc_en that shall be translated as well.

**Comment by mkulesh** [comment]
Dear @Symbian9, I fixed all points related to the app full/short name. If it is OK for you, please close the issue.

**Comment by mkulesh** [comment]
Dear @Symbian9, thank you very math for translation review. All points that you mentioned are fixed. If it is OK for you, please close the issue.

**Comment by Symbian9** [comment]
@mkulesh, thank You for the great app!

P.S.: hope that development of it would be increased since now it is FLOSS alternative to Mathcad & SMath Studio
