### ISSUE TITLE
implement color themes

### ISSUE THREAD

**Issue by KOLANICH** [mkulesh/microMathematics#40]
Black themes are usually more friendly to the devices with amoled screens. Also some users may want to have other color themes.

**Comment by mkulesh** [comment]
To implement themes, old navigation drawer and status bar shall be replaced by modern components from support design library, see #43. I already started to integrate support design library. When this library will be integrated, I can start with this issue.

**Comment by mkulesh** [comment]
Hi @KOLANICH, I already committed integration of android support design library and re-worked the design of the main activity. Please take a look on this new design. I plan to release first the next version with this new design and than start to implement themes.

**Comment by mkulesh** [comment]
Dear @KOLANICH, the first draft is committed: there are currently three themes available, the theme can be selected in the application settings. Please take a look on this new design. If you want to add your own theme, lease look at [this commit](https://github.com/mkulesh/microMathematics/commit/f6a9127dfd272ad60609bd92135d5a9111b51eb2)

**Comment by KOLANICH** [comment]
Yhank you, but for now I cannot test - the version in F-Droid ilacks this functionality for now. And I think that it may be nice to have the possibility to load a theme from a file.

**Comment by Symbian9** [comment]
> Thank you, but for now I cannot test - the version in F-Droid ilacks this functionality for now.

@KOLANICH, you always can get latest autobuild from here as APK (before install it just remove existed μMath+ from your device!)

- https://github.com/mkulesh/microMathematics/tree/autobuild/autobuild

> And I think that it may be nice to have the possibility to load a theme from a file.

+1. Yeah, it would be cool if add submenu entry "App settings -> App theme -> Load from file ...".

**Comment by Symbian9** [comment]
@mkulesh, as good tradition to apps themes design, every app should has at least one "Light/Day" and one "Dark/Night" themes.

So, please, add "Light" & "Dark" themes to μMath+ too! ;-)

- "Light" - black&white/grayscale theme with black/dark text on white/light background
- "Dark" - white&black/grayscale theme with white/light text on black/dark background

**Comment by mkulesh** [comment]
Dear @Symbian9, currently, there are three "Light" themes and one "Dark" theme. Please take a look on the latest autobuild on https://github.com/mkulesh/microMathematics/tree/autobuild/autobuild

**Comment by Symbian9** [comment]
> Please take a look on the latest

OK, I just test it and found that on Dark theme some bundled images look not good - need add light stroke on dark elements

![svg issues](http://hnng.moe/f/XvA)

So, please, test all bundled SVG images and add strokes to each fill.

> there are three "Light" themes and one "Dark" theme.

I highly recommend you name those themes as:

- "Light (Indigo & Orange)"
- "Light (Teal & Deep Orange)"
- "Light (Gray & Indigo)"
- "Dark (Dim Gray & Cyan)"

**Comment by mkulesh** [comment]
Dear @Symbian9, thank you for response, I totally agree with your proposals regarding SVG images and theme names. It is done, please re-test.

**Comment by Symbian9** [comment]
Well, now its look much better.

I found that you also fixed some unclosed path with outlines in SVG images in latest build - it's good, because I also sew those issues with unclosed outlines in previous build ;-)

**Comment by mkulesh** [comment]
> And I think that it may be nice to have the possibility to load a theme from a file.
The theme contains currently not only colors, but also some drawables (for example, background images for dialog window). This make loading of theme from a file difficult. I think, we can skip this feature at current stage, and consider the theme export later, when dialog windows will be re-designed. At this stage, if you agree, I will label this issue as implemented.

**Comment by KOLANICH** [comment]
>This make loading of theme from a file difficult.

What's wrong with using a zip (or any other) archive for a theme file?

**Comment by mkulesh** [comment]
Dear @KOLANICH, the current implementation is based on the standard themes framework, where color theme is pre-compiled, i.e. this framework does not support dynamically loaded theme. The dialog background images are currently android-drawables that shall be pre-compiled as well. I think, it is really difficult to use dynamically loaded theme at this stage.

**Comment by KOLANICH** [comment]
Thank you for the explanation.

**Comment by Symbian9** [comment]
For the record, maybe, it would be usefull add strong "E-Ink (Black and White)" theme, with only black on white background (without grayscale) for  Android devices with E-Ink displays.

**Comment by mkulesh** [comment]
Hi @Symbian9, it is a good proposal, I will plan it for release 2.16.1.

**Comment by mkulesh** [comment]
Hi @Symbian9, I created new issue #54 that covers your proposal related to strong light and dark themes. The themes framework in uMath is fully implemented and tested. Therefore, I would like to close this issue.
