### ISSUE TITLE
Disable zooming during editing mode

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#44]
Its hard to edit document that could be zoomed if mistakenly touch screen by two fingers during editing.

So, dissable zooming in editing mode.

**Comment by mkulesh** [comment]
Dear Symbian9, I implemented your proposal. Now, if any editor field in the document is focused (a cursor is visible), the zoom mode is disabled. It is enabled again on leaving the editor field (when cursor disappears). However, there is an exception: zoom mode still be active when entering the special editor field in the math. palette panel (when you long press any formula term). Is it that you mentioned in this issue? Please also check whether #52 "Add "Lock Zoom" option (during editing/reading)" duplicates this issue.

**Comment by Symbian9** [comment]
> However, there is an exception: zoom mode still be active when entering the special editor field in the math. palette panel (when you long press any formula term). Is it that you mentioned in this issue?

Yes.

**Comment by mkulesh** [comment]
Dear @Symbian9, please test the current implementation and close the issue if this implementation is as desired.

**Comment by Symbian9** [comment]
Well, "Lock zooming during editing" work.

**Comment by mkulesh** [comment]
Will be released in 2.16
