### ISSUE TITLE
Create page on AlternativeTo wiki

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#47]
Propose create page
* https://alternativeto.net/software/micromathematics-plus/

As example, look on
* https://alternativeto.net/software/smath-studio-desktop/
* https://alternativeto.net/software/mathcad/

**Comment by mkulesh** [comment]
Thanks a lot, it is a good idea, I will do it

**Comment by Symbian9** [comment]
Also, look how apps for Android represented on AlternativeTo
- https://alternativeto.net/platform/android/

**Comment by mkulesh** [comment]
Hi @Symbian9, I created the page: https://alternativeto.net/software/micromathematics-plus/
Now it is waiting for approval. Do you have any suggestions for the page content?

**Comment by mkulesh** [comment]
https://alternativeto.net/software/micromathematics-plus is now approved
