### ISSUE TITLE
Porting to Qt5 (for Desktop & Mobile)

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#48]
Since *μMath+* now look great, it would be cool make desktop version of it.

But at this moment Java-based apps on desktop not too popular and Java also on many PC's not installed (or users won't install and use Java anymore), so itcwould be cool try make port (as separate branch) rewrited to Qt5, that will give a chance make it usable on not only on Android, but on Linux, macOS, Windows and many other OS where Qt5 already ported too.

TODO
- Design original *Mobile* UI using QtDesigner (as `.ui` files);
  - Design *Desktop* similar to original *Mobile* UI;
  - Create minimal number of shortcuts for *Desktop* with keyboard;
- Make port of *μMath+ core* to `C++`;
- ...

P.S.: This is long-term feature request.

**Comment by KOLANICH** [comment]
I gues it's not needed: we already have python, scipy,  sympy, scikitlearn, jupyter notebook, Mathics, Wolfram Mathematica, gnu octave. There are ports of maxima and octave on android, python-based tools also work fine. I guess it makes sense not to reinvent a wheel but to use them as backends.

**Comment by mkulesh** [comment]
I also guess it's not needed. There is SMath Studio that is a really good desktop alternative to uMath+. I think it is much better to  implement import/export to SMath Studio as proposed in #38. I now discussing this question with Andrey Ivashov, the author of SMath Studio.

**Comment by Symbian9** [comment]
OK. So, try implement https://github.com/mkulesh/microMathematics/issues/48

**Comment by yashpalgoyal1304** [comment]
Technical-ish reasons against some of mentioned alternates:
* SMath Studio, wolfram are proprietary
* *py (python, scipy, sympy, jupyter) all require knowledge of python and packages etc

Technical-ish reason in favour of micromaths:
* It's FOSS
* Being a single purpose package, it is extremely lean and minimal (but still capable)
* ... so it can be used in extremely relaxed environment as
    * not much syntactic debt and requirement of rigour is there in first place
    * no mental burden of learn in depth lest FOMO on opportunities (as with other packages)
* Ability to export the following is super nice
    * all plots as images automatically
    * whole worksheet as a .TeX file

Personal reasons in favour of proposal in this issue:
* Lack of time to immediately learn intricacies and rigidities of other languages/packages
* Micromaths sufficiently fulfils my current needs
* ∴ many of my docs are done in it, & having those on desktop for self-documentation for later would be nice

But ohkay
* ... even if it's not wanted here in this repo, 
* ... can some info/tips/general directions be shared on how the port to linux be done? 
* ... for someone else can pick up the undertaking themselves if they so wish
