### ISSUE TITLE
Add info about creating/editing locales and translating docs (in README.md or as wiki)

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#5]
Here are few apps that could be helpfull specially for Android users

* https://f-droid.org/wiki/page/io.github.lonamiwebs.stringlate
* https://f-droid.org/wiki/page/jp.forkhub

**Comment by Symbian9** [comment]
Related

* https://github.com/mkulesh/microMathematics/issues/4#issuecomment-323181405

Cast @Poussinou

**Comment by Symbian9** [comment]
Here is issue related to docs: Russian PDF output different from English & Deutsch PDF's (different fonts and drop caps)

![PDF issues](http://hnng.moe/f/TUG)

Also, as described above in Russian output its look like `M` separated from `icroMathematics Plus`.

As I already proposed, use always `microMathematics Plus` (without uppercased `M`), and its no matter is it placed on start of paragraph/sentense or not.

**Comment by Poussinou** [comment]
I'm trying to translate the strings.xml file (I've not to much time to work on this right now). As I was saying earlier, this could be a good idea to use an external service (transifex is the best for me, and it is free-as-in-free-beer for open source projects) you can add every files you want to be translated, manage the different locales...

**Comment by Poussinou** [comment]
It's an interesting tool for such a big project

**Comment by Symbian9** [comment]
> As I was saying earlier, this could be a good idea to use an external service

There is Weblate service for such things...

* http://weblate.org

...but for interact with μMath+ repo using Weblate need some additional setups by repositary owner.

@mkulesh, what You think about adding Weblate support to your this repo?

**Comment by mkulesh** [comment]
@Symbian9 Unfortunately, I am not able to use the same (identical) fonts in Russian and English documentation since my LaTeX installation
```
pdflatex --version
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)
```
just not have identical fonts. If you are familiar with texlive, could you please take a look on microMathematics-ru.sty and fix fonts settings in this style file?

**Comment by Symbian9** [comment]
> If you are familiar with texlive


Saddly, I'm not use LaTeX/TeX (at least not yet)

**Comment by Symbian9** [comment]
Found **Stringlate** app very friendly for creating and editing locales

![Stringlate projects list](http://hnng.moe/f/TVB)

![Stringlate lacale editing](http://hnng.moe/f/TVC)

**Comment by mkulesh** [comment]
Thank you for sharing this information. I'll take a look on this app.

**Comment by Poussinou** [comment]
I'm also using it :) but you cannot translate the docs with it

**Comment by mkulesh** [comment]
I added wiki page https://github.com/mkulesh/microMathematics/wiki

As you can see from this page, the full APP translation can not be done automatically using any of the proposed tools since the documentation structure is complex. The partial translation (that means the GUI is localized, but the documentation still be in English) is may be possible with these tools.

**Comment by Symbian9** [comment]
> I'm also using it :) but you cannot translate the docs with it

I add feature request for such additional functionality for **Stringlate**, hope its developers could implement it soon

* https://github.com/LonamiWebs/Stringlate/issues/124

**Comment by Symbian9** [comment]
For translators: Stringlate app updated to v0.10
* https://github.com/LonamiWebs/Stringlate/releases/tag/v0.10
