### ISSUE TITLE
Can't install autobuild N.76

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#51]
When try install autobuild N.76 my device say that it could not be installed

- https://github.com/mkulesh/microMathematics/commit/4b2e11183a43a50632a74387ff1552d64d494e62

OS: Android 6.0
Device: ASSISTANT AS-5432

**Comment by mkulesh** [comment]
It happens some time with autobuilds since it is not signed. To solve the problem, please manually de-install existing application and than try to install autobuild again
