### ISSUE TITLE
Add "Lock Zoom" option in read-only mode

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#52]
During editing & reading some time mistakenly zoom changed.

Please, add "Lock Zoom" option for prevent mistaken change of zoom level.

P.S.: Also, it would usefull add "Reset Zoom" option too.

**Comment by mkulesh** [comment]
Hi @Symbian9, does this issue possible duplicate #44 "Disable zooming during editing mode"?

**Comment by mkulesh** [comment]
Hi @Symbian9, I can expand the "Document settings" dialog (see "Document settings" command from main menu) by a new check-box "Enable zoom" that will be checked-on by default, as in the attached screenshot. Shall this solution solve this issue?
![device-2018-01-07-222135](https://user-images.githubusercontent.com/30557348/34654240-53b8280e-f3f9-11e7-9a63-46a68a9ab60f.png)

**Comment by mkulesh** [comment]
Hi Symbian9, I implement this feature as shown on screenshot above. Please test using the current autobuild (version 2.17.1)

**Comment by Symbian9** [comment]
Why this option added in "Document" setting?

This option should be in "App settings"!

**Comment by mkulesh** [comment]
Hi Symbian9,

> Why this option added in "Document" setting?

because I proposed this solution two month ago and you accepted this proposal by putting an "Up emoji", see my comment from Jan 7 above :)
However, you are right, "App settings" is much better place for such a parameter than "Document settings". Now, I moved it into "App settings", please take a look.

**Comment by mkulesh** [comment]
![application_settings](https://user-images.githubusercontent.com/30557348/37370474-a6d6e3a4-270c-11e8-95ca-a95323af9d4a.png)

Please test and close the issue if it is ok.

**Comment by Symbian9** [comment]
"Zoom lock" work, but where "read-only" option now?

**Comment by mkulesh** [comment]
Hi @Symbian9, is there any remaining work on this issue? That do you mean with "read-only" option?
