### ISSUE TITLE
Add contrast light and dark themes

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/microMathematics#54]
For the record, maybe, it would be usefull
- add strong light *"E-Ink (Black on White)"* theme, with only black on white background (without grayscale) for E-Ink devices.
- add strong dark "Amoled (White on Black)" theme, with only white on black background (without grayscale) for Amoled devices.

**Comment by Symbian9** [comment]
Just for the record
- https://www.reddit.com/r/androidapps/comments/7qf3lp/does_using_an_amoled_backgrounds_in_apps_really/

**Comment by mkulesh** [comment]
Hi Symbian9, both strong light and dark themes are now available. Could you please test both temes? Do you have any E-Ink or Amoled devices in order to try these themes?

**Comment by mkulesh** [comment]
Hi Symbian9,
the issue is implemented. Please test and close the issue if it is ok.

**Comment by mkulesh** [comment]
Implemented and released in 2.17.1
