### ISSUE TITLE
Implement units

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/microMathematics#61]

**Comment by mkulesh** [comment]
Basic units processing:

![units](https://user-images.githubusercontent.com/30557348/35885464-2c4525d6-0b8e-11e8-9d2f-afa9053fa2c8.png)

**Comment by mkulesh** [comment]
Released in version 2.17.0

**Comment by Magicrafter13** [comment]
Not sure if this is worth opening a new GitHub issue over, but some way to input nonstandard characters (like Greek letters) without relying on the user installing a specialized keyboard would be nice.
