### ISSUE TITLE
Ask on exit/closing app

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#65]
Add an option in "App settings" that will help prevent closing app on single click "Back" button.

**Comment by mkulesh** [comment]
Hi Symbian9
the issue is implemented:

![application_settings](https://user-images.githubusercontent.com/30557348/37370474-a6d6e3a4-270c-11e8-95ca-a95323af9d4a.png)

Please test and close the issue if it is ok.

**Comment by Symbian9** [comment]
Well done! ;-)

NOTE: As for me, it would be better if this option switch to "ON" by default.
