### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#7]
Add possibility export directly in PDF using iTextPDF library (or any other)

* https://github.com/itext/itextpdf

There are few open-source apps that could be used as reference or examples

* https://github.com/scoute-dich/PDFCreator
* https://github.com/pratikbutani/Android-PDF
* https://github.com/apjoex/PDFMaker
* https://github.com/sotrh/android_print_demo

It could be usefull also add few document design templates or some settings on customizing look of output PDF.

**Comment by lonetech** [comment]
We have some sort of HTML export. Might one suitable workaround be to use that then WebView to print to PDF?
https://developer.android.com/training/printing/html-docs

**Comment by mkulesh** [comment]
No possibility to do it
