### ISSUE TITLE
Units for Telecoms

### ISSUE THREAD

**Issue by gatopeich** [mkulesh/microMathematics#71]
I would love to have the following units present:
bits, Kbps, Mbps, Gbps, bytes := 8 bits, KB, MB, GB

**Comment by mkulesh** [comment]
Hi @gatopeich,
many thank for the proposal and sorry for late response. Now, units of information are available. If you want to test it, please install the latest autobuild and open there the attached file (please note I attached a *.zip archive of *.mmt file, it shall be uncompressed before opening)
[units_of_information.mmt.zip](https://github.com/mkulesh/microMathematics/files/1950976/units_of_information.mmt.zip)

This example is also included in the Resources of uMath+ and can be also opened using main menu "Open" - > "Resources of uMath+" -> units_of_information.mmt

**Comment by gatopeich** [comment]
Thank you very much, it works like a charm!

**Comment by mkulesh** [comment]
Ready to be delivered with version 2.17.2
