### ISSUE TITLE
Implement logarithmic scale for function plot

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/microMathematics#74]

**Comment by jinx100** [comment]
Here's an mmt file which has some problems if I try adding a log scaled x range to a plot. The x and y lists seem to be created. Oops, can't drop it even disguised as text or xlsx. Trying code box.

`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<micromath xmlns:mmt="http://micromath.mkulesh.com">
  <formulaList documentVersion="2" author="ken" title="log scales" description="problem if log spacing (x2) used in a plot" textWidth="60" significantDigits="6" scale="0.54053" redefineAllowed="false">
    <text_fragment>
      <term key="text" text="My try at log scales&#10;&#10;Fails if x2 used in a plot&#10;" />
    </text_fragment>
    <equation>
      <term key="leftTerm" text="N" />
      <term key="rightTerm" text="20" />
    </equation>
    <equation>
      <term key="leftTerm" text="Xint" />
      <term key="rightTerm" text="0.1" />
    </equation>
    <equation>
      <term key="leftTerm" text="Xend" />
      <term key="rightTerm" text="10" />
    </equation>
    <equation>
      <term key="leftTerm" text="N2" />
      <term key="rightTerm" code="equidistant_interval">
        <term key="minValue" text="0" />
        <term key="nextValue" text="1" />
        <term key="maxValue" text="N" />
      </term>
    </equation>
    <equation>
      <term key="leftTerm" text="x1" />
      <term key="rightTerm" code="equidistant_interval">
        <term key="minValue" text="Xint" />
        <term key="nextValue" code="plus">
          <term key="leftTerm" text="Xint" />
          <term key="rightTerm" code="divide">
            <term key="leftTerm" code="minus">
              <term key="leftTerm" text="Xend" />
              <term key="rightTerm" text="Xint" />
            </term>
            <term key="rightTerm" text="N" />
          </term>
        </term>
        <term key="maxValue" text="Xend" />
      </term>
    </equation>
    <result inRightOfPrevious="true" disableCalculation="false" hideResultField="false" arrayLength="7">
      <term key="leftTerm" text="x1" />
      <term key="rightTerm" text="[[0.1], [0.595], [1.09], [1.585], [2.08], [2.575], [...], [10.0]]" />
    </result>
    <equation>
      <term key="leftTerm" text="x2" />
      <term key="rightTerm" code="mult">
        <term key="leftTerm" text="Xint" />
        <term key="rightTerm" code="power">
          <term key="leftTerm" code="divide">
            <term key="leftTerm" text="Xend" />
            <term key="rightTerm" text="Xint" />
          </term>
          <term key="rightTerm" code="divide">
            <term key="leftTerm" text="N2" />
            <term key="rightTerm" text="N" />
          </term>
        </term>
      </term>
    </equation>
    <result inRightOfPrevious="true" disableCalculation="false" hideResultField="false" arrayLength="7">
      <term key="leftTerm" text="x2" />
      <term key="rightTerm" text="[[0.1], [0.125893], [0.158489], [0.199526], [0.251189], [0.316228], [...], [10.0]]" />
    </result>
    <equation>
      <term key="leftTerm" text="y1(x1)" />
      <term key="rightTerm" code="sqrt_layout">
        <term key="argTerm" text="x1" />
      </term>
    </equation>
    <result inRightOfPrevious="true" disableCalculation="false" hideResultField="false" arrayLength="7">
      <term key="leftTerm" code="content:com.mkulesh.micromath.link.y1">
        <term key="argTerm" text="x1" />
      </term>
      <term key="rightTerm" text="[[0.316228], [0.771362], [1.04403], [1.25897], [1.44222], [1.60468], [...], [3.16228]]" />
    </result>
    <result inRightOfPrevious="true" disableCalculation="false" hideResultField="false" arrayLength="7">
      <term key="leftTerm" code="content:com.mkulesh.micromath.link.y1">
        <term key="argTerm" text="x2" />
      </term>
      <term key="rightTerm" text="[[0.316228], [0.354813], [0.398107], [0.446684], [0.501187], [0.562341], [...], [3.16228]]" />
    </result>
    <equation>
      <term key="leftTerm" text="y2(x)" />
      <term key="rightTerm" text="x" />
    </equation>
    <result inRightOfPrevious="true" disableCalculation="false" hideResultField="false" arrayLength="7">
      <term key="leftTerm" code="content:com.mkulesh.micromath.link.y2">
        <term key="argTerm" text="x1" />
      </term>
      <term key="rightTerm" text="[[0.1], [0.595], [1.09], [1.585], [2.08], [2.575], [...], [10.0]]" />
    </result>
    <result inRightOfPrevious="true" disableCalculation="false" hideResultField="false" arrayLength="7">
      <term key="leftTerm" code="content:com.mkulesh.micromath.link.y2">
        <term key="argTerm" text="x2" />
      </term>
      <term key="rightTerm" text="[[0.1], [0.125893], [0.158489], [0.199526], [0.251189], [0.316228], [...], [10.0]]" />
    </result>
    <equation>
      <term key="leftTerm" text="y3(x)" />
      <term key="rightTerm" code="power">
        <term key="leftTerm" text="x" />
        <term key="rightTerm" text="2" />
      </term>
    </equation>
    <result inRightOfPrevious="true" disableCalculation="false" hideResultField="false" arrayLength="7">
      <term key="leftTerm" code="content:com.mkulesh.micromath.link.y3">
        <term key="argTerm" text="x1" />
      </term>
      <term key="rightTerm" text="[[0.01], [0.354025], [1.1881], [2.51222], [4.3264], [6.63063], [...], [100.0]]" />
    </result>
    <result inRightOfPrevious="true" disableCalculation="false" hideResultField="false" arrayLength="7">
      <term key="leftTerm" code="content:com.mkulesh.micromath.link.y3">
        <term key="argTerm" text="x2" />
      </term>
      <term key="rightTerm" text="[[0.01], [0.0158489], [0.0251189], [0.0398107], [0.0630957], [0.1], [...], [100.0]]" />
    </result>
    <text_fragment>
      <term key="text" text="&#10;Test Plots  X,Y Scales&#10;" />
    </text_fragment>
    <text_fragment>
      <term key="text" text="Lin,Lin" />
    </text_fragment>
    <plot_function width="586" height="586" axes_style="boxed" xLabelsNumber="4" yLabelsNumber="4" gridLineColor="#FFE0E0E0" xType="linear" yType="linear" functionsNumber="3">
      <term key="yMaxValue" text="" />
      <term key="yFunction1" color="#FF0000FF" width="3" lineStyle="solid" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y1">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yFunction2" color="#FFFF0080" width="3" lineStyle="dashed" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y2">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yFunction3" color="#FF999900" width="3" lineStyle="dotted" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y3">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yMinValue" text="" />
      <term key="xMinValue" text="" />
      <term key="xFunction1" text="x1" />
      <term key="xFunction2" text="x1" />
      <term key="xFunction3" text="x1" />
      <term key="xMaxValue" text="" />
    </plot_function>
    <text_fragment>
      <term key="text" text="Lin,Log" />
    </text_fragment>
    <plot_function width="586" height="586" axes_style="boxed" xLabelsNumber="4" yLabelsNumber="4" gridLineColor="#FFE0E0E0" xType="linear" yType="log10" functionsNumber="3">
      <term key="yMaxValue" text="" />
      <term key="yFunction1" color="#FF0000FF" width="3" lineStyle="solid" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y1">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yFunction2" color="#FFFF0080" width="3" lineStyle="dashed" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y2">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yFunction3" color="#FF999900" width="3" lineStyle="dotted" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y3">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yMinValue" text="0.01" />
      <term key="xMinValue" text="" />
      <term key="xFunction1" text="x1" />
      <term key="xFunction2" text="x1" />
      <term key="xFunction3" text="x1" />
      <term key="xMaxValue" text="" />
    </plot_function>
    <text_fragment>
      <term key="text" text="Log,Lin" />
    </text_fragment>
    <plot_function width="586" height="586" axes_style="boxed" xLabelsNumber="4" yLabelsNumber="4" gridLineColor="#FFE0E0E0" xType="log10" yType="linear" functionsNumber="3">
      <term key="yMaxValue" text="" />
      <term key="yFunction1" color="#FF0000FF" width="3" lineStyle="solid" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y1">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yFunction2" color="#FFFF0080" width="3" lineStyle="dashed" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y2">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yFunction3" color="#FF999900" width="3" lineStyle="dotted" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y3">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yMinValue" text="0.01" />
      <term key="xMinValue" text="" />
      <term key="xFunction1" text="x1" />
      <term key="xFunction2" text="x1" />
      <term key="xFunction3" text="x1" />
      <term key="xMaxValue" text="" />
    </plot_function>
    <text_fragment>
      <term key="text" text="Log,Log" />
    </text_fragment>
    <plot_function width="586" height="586" axes_style="boxed" xLabelsNumber="4" yLabelsNumber="4" gridLineColor="#FFE0E0E0" xType="log10" yType="log10" functionsNumber="3">
      <term key="yMaxValue" text="" />
      <term key="yFunction1" color="#FF0000FF" width="3" lineStyle="solid" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y1">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yFunction2" color="#FFFF0080" width="3" lineStyle="dashed" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y2">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yFunction3" color="#FF999900" width="3" lineStyle="dotted" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y3">
        <term key="argTerm" text="x1" />
      </term>
      <term key="yMinValue" text="0.01" />
      <term key="xMinValue" text="" />
      <term key="xFunction1" text="x1" />
      <term key="xFunction2" text="x1" />
      <term key="xFunction3" text="x1" />
      <term key="xMaxValue" text="" />
    </plot_function>
  </formulaList>
</micromath>`

**Comment by jinx100** [comment]
I see now a calculated sequence cannot be used in a plot. Maybe modify the builtin sequence generator to accept Xstart, Xend and number of spaces with a choice of linear or geometric spacing. This would give even spacing on log plots.

**Comment by mkulesh** [comment]
Hi @jinx100 , thanks for testing this issue. The problem is that your x2 variable indirectly uses N2 index. Confusing is, that an inderict variable can be shown in a text result view, but con not be used in a plot. You can change x2 to an array and it will work fine.

**Comment by jinx100** [comment]
That does work well. Thank you.

**Comment by mkulesh** [comment]
Ready to be delivered with version 2.17.2
