### ISSUE TITLE
3D Plot with indexed variable

### ISSUE THREAD

**Issue by jinx100** [mkulesh/microMathematics#75]
A 3D plot y(x1,x2) does plot y against x1 and x2. If one of the variables is indexed, say y(x1[N],x2), then the plot axes are N and x2. Shouldn't the axes be x1[N] and x2? An example is attached. 
Even zip won't work so 

`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<micromath xmlns:mmt="http://micromath.mkulesh.com">
  <formulaList documentVersion="2" author="ken" title="dog_river" description="" textWidth="60" significantDigits="6" scale="0.48428" redefineAllowed="true">
    <text_fragment>
      <term key="text" text="Dog swims across river.&#10;From Xint,Yint toward dock at 0,0.&#10;rdv is current/dog speed &lt;1.0&#10;" />
    </text_fragment>
    <equation>
      <term key="leftTerm" text="Xint" />
      <term key="rightTerm" text="2.0" />
    </equation>
    <equation inRightOfPrevious="true">
      <term key="leftTerm" text="Yint" />
      <term key="rightTerm" text="1.0" />
    </equation>
    <equation>
      <term key="leftTerm" text="rdv1" />
      <term key="rightTerm" text="0.3" />
    </equation>
    <equation inRightOfPrevious="true">
      <term key="leftTerm" text="rdv2" />
      <term key="rightTerm" text="0.5" />
    </equation>
    <equation inRightOfPrevious="true">
      <term key="leftTerm" text="rdv3" />
      <term key="rightTerm" text="0.7" />
    </equation>
    <equation>
      <term key="leftTerm" text="C(rdv)" />
      <term key="rightTerm" code="mult">
        <term key="leftTerm" code="power">
          <term key="leftTerm" text="Xint" />
          <term key="rightTerm" text="rdv" />
        </term>
        <term key="rightTerm" code="identity">
          <term key="argTerm" code="divide_slash">
            <term key="leftTerm" text="Xint" />
            <term key="rightTerm" code="plus">
              <term key="leftTerm" text="Yint" />
              <term key="rightTerm" code="sqrt_layout">
                <term key="argTerm" code="plus">
                  <term key="leftTerm" code="power">
                    <term key="leftTerm" text="Xint" />
                    <term key="rightTerm" text="2" />
                  </term>
                  <term key="rightTerm" code="power">
                    <term key="leftTerm" text="Yint" />
                    <term key="rightTerm" text="2" />
                  </term>
                </term>
              </term>
            </term>
          </term>
        </term>
      </term>
    </equation>
    <equation>
      <term key="leftTerm" text="N1" />
      <term key="rightTerm" text="200" />
    </equation>
    <equation inRightOfPrevious="true">
      <term key="leftTerm" text="x" />
      <term key="rightTerm" code="equidistant_interval">
        <term key="minValue" text="0" />
        <term key="nextValue" code="divide">
          <term key="leftTerm" text="Xint" />
          <term key="rightTerm" text="N1" />
        </term>
        <term key="maxValue" text="Xint" />
      </term>
    </equation>
    <equation>
      <term key="leftTerm" text="y(x,rdv)" />
      <term key="rightTerm" code="mult">
        <term key="leftTerm" code="divide">
          <term key="leftTerm" text="1" />
          <term key="rightTerm" text="2" />
        </term>
        <term key="rightTerm" code="minus">
          <term key="leftTerm" code="divide">
            <term key="leftTerm" code="power">
              <term key="leftTerm" text="x" />
              <term key="rightTerm" code="identity">
                <term key="argTerm" code="plus">
                  <term key="leftTerm" text="rdv" />
                  <term key="rightTerm" text="1" />
                </term>
              </term>
            </term>
            <term key="rightTerm" code="content:com.mkulesh.micromath.link.C">
              <term key="argTerm" text="rdv" />
            </term>
          </term>
          <term key="rightTerm" code="divide">
            <term key="leftTerm" code="content:com.mkulesh.micromath.link.C">
              <term key="argTerm" text="rdv" />
            </term>
            <term key="rightTerm" code="power">
              <term key="leftTerm" text="x" />
              <term key="rightTerm" code="identity">
                <term key="argTerm" code="minus">
                  <term key="leftTerm" text="rdv" />
                  <term key="rightTerm" text="1" />
                </term>
              </term>
            </term>
          </term>
        </term>
      </term>
    </equation>
    <text_fragment>
      <term key="text" text="&#10;More points near zero&#10;" />
    </text_fragment>
    <equation>
      <term key="leftTerm" text="N" />
      <term key="rightTerm" code="equidistant_interval">
        <term key="minValue" text="0" />
        <term key="nextValue" text="1" />
        <term key="maxValue" text="N1" />
      </term>
    </equation>
    <equation>
      <term key="leftTerm" text="x1[N]" />
      <term key="rightTerm" code="mult">
        <term key="leftTerm" text="Xint" />
        <term key="rightTerm" code="power">
          <term key="leftTerm" code="divide">
            <term key="leftTerm" code="content:com.mkulesh.micromath.index.x">
              <term key="argTerm" text="N" />
            </term>
            <term key="rightTerm" text="Xint" />
          </term>
          <term key="rightTerm" text="4" />
        </term>
      </term>
    </equation>
    <equation>
      <term key="leftTerm" text="y2(x)" />
      <term key="rightTerm" text="0.0" />
    </equation>
    <text_fragment>
      <term key="text" text="&#10;Path with various currents&#10;" />
    </text_fragment>
    <plot_function width="667" height="667" axes_style="boxed" xLabelsNumber="4" yLabelsNumber="4" gridLineColor="#FFE0E0E0" xType="linear" yType="linear" functionsNumber="4">
      <term key="yMaxValue" text="" />
      <term key="yFunction1" color="#FF0000FF" width="6" lineStyle="solid" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y:2">
        <term key="argTerm1" text="x" />
        <term key="argTerm2" text="rdv1" />
      </term>
      <term key="yFunction2" color="#FFFF0080" width="6" lineStyle="dashed" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y:2">
        <term key="argTerm1" text="x" />
        <term key="argTerm2" text="rdv2" />
      </term>
      <term key="yFunction3" color="#FF008A39" width="6" lineStyle="dotted" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y:2">
        <term key="argTerm1" text="x" />
        <term key="argTerm2" text="rdv3" />
      </term>
      <term key="yFunction4" color="#FF003899" width="5" lineStyle="dash_dot" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y2">
        <term key="argTerm" text="x" />
      </term>
      <term key="yMinValue" text="" />
      <term key="xMinValue" text="" />
      <term key="xFunction1" text="x" />
      <term key="xFunction2" text="x" />
      <term key="xFunction3" text="x" />
      <term key="xFunction4" text="x" />
      <term key="xMaxValue" text="" />
    </plot_function>
    <text_fragment>
      <term key="text" text="&#10;Close to zero&#10;" />
    </text_fragment>
    <plot_function width="688" height="688" axes_style="boxed" xLabelsNumber="4" yLabelsNumber="4" gridLineColor="#FF787878" xType="linear" yType="linear" functionsNumber="2">
      <term key="yMaxValue" text="0.2" />
      <term key="yFunction1" color="#FF0000FF" width="6" lineStyle="solid" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y:2">
        <term key="argTerm1" code="content:com.mkulesh.micromath.index.x1">
          <term key="argTerm" text="N" />
        </term>
        <term key="argTerm2" text="0.8" />
      </term>
      <term key="yFunction2" color="#FFFF0080" width="6" lineStyle="dashed" shapeType="none" shapeSize="300" code="content:com.mkulesh.micromath.link.y:2">
        <term key="argTerm1" text="x" />
        <term key="argTerm2" text="0.8" />
      </term>
      <term key="yMinValue" text="-0.3" />
      <term key="xMinValue" text="" />
      <term key="xFunction1" code="content:com.mkulesh.micromath.index.x1">
        <term key="argTerm" text="N" />
      </term>
      <term key="xFunction2" text="x" />
      <term key="xMaxValue" text="0.01" />
    </plot_function>
    <equation>
      <term key="leftTerm" text="p2" />
      <term key="rightTerm" code="equidistant_interval">
        <term key="minValue" text="0.3" />
        <term key="nextValue" text="0.35" />
        <term key="maxValue" text="0.8" />
      </term>
    </equation>
    <text_fragment>
      <term key="text" text="&#10;3D Plot&#10;" />
    </text_fragment>
    <plot_contour plotStyle="surface" width="667" height="667" axes_style="boxed" meshLines="false" meshFill="true" meshOpacity="181" rotation="335" elevation="20" xLabelsNumber="4" yLabelsNumber="4" gridLineColor="#FFE0E0E0" xType="linear" yType="linear" zLabelsNumber="10" colorMap="coldhot">
      <term key="yMaxValue" text="" />
      <term key="yMinValue" text="" />
      <term key="xMinValue" text="" />
      <term key="zFunction" code="content:com.mkulesh.micromath.link.y:2">
        <term key="argTerm1" text="x" />
        <term key="argTerm2" text="p2" />
      </term>
      <term key="xMaxValue" text="" />
    </plot_contour>
    <text_fragment>
      <term key="text" text="&#10;Axis should be x1[N] not N?&#10;" />
    </text_fragment>
    <plot_contour plotStyle="surface" width="667" height="667" axes_style="boxed" meshLines="false" meshFill="true" meshOpacity="181" rotation="335" elevation="20" xLabelsNumber="4" yLabelsNumber="4" gridLineColor="#FFE0E0E0" xType="linear" yType="linear" zLabelsNumber="10" colorMap="coldhot">
      <term key="yMaxValue" text="" />
      <term key="yMinValue" text="" />
      <term key="xMinValue" text="" />
      <term key="zFunction" code="content:com.mkulesh.micromath.link.y:2">
        <term key="argTerm1" code="content:com.mkulesh.micromath.index.x1">
          <term key="argTerm" text="N" />
        </term>
        <term key="argTerm2" text="p2" />
      </term>
      <term key="xMaxValue" text="" />
    </plot_contour>
  </formulaList>
</micromath>`

**Comment by mkulesh** [comment]
Hi @jinx100,
Sorry for the radio silence for a while, I worked for an other project last time.
I expanded the plots. Now it is possible to use an array variable as a plot parameter directly without an index. It means the axis range will now be equal to the array values range instead of index range. A new example scaled_axis.mmt is now available in the resources of the app (committed as https://github.com/mkulesh/microMathematics/blob/master/app/src/main/assets/examples/scaled_axis.mmt). If you like to test it please install the latest nightly build and take a look on this example.

**Comment by jinx100** [comment]
Hi Mikhail,

Thanks for the fix!

Just for fun I applied it to your 3-D plot example (attached) and the
result is not interesting.

Ken

**Comment by jinx100** [comment]
Mikhail,

Here is a better way to show this option.

Ken

**Comment by mkulesh** [comment]
Hi @jinx100 
thank you for testing. Unfortunately I am not able to see your attachments. Could you please send it me per email on mikhail.kulesh@gmail.com?

**Comment by mkulesh** [comment]
Hi @jinx100,
thank you for the examples. I found your version of scaled_axis.mmt better than my. It is now committed and I will release it in the version 2.20.2

**Comment by mkulesh** [comment]
Released in version 2.20.1
