### ISSUE TITLE
Poor swiping scrolling controls

### ISSUE THREAD

**Issue by nyanpasu64** [mkulesh/microMathematics#76]
Moto G5 Plus, rooted, Magisk and Xposed, Android 7.0.
Tested on latest microMathematics+ on F-Droid and microMathematics on Play Store.

The app feels very uncomfortable to use because of poor swiping controls. I would say the app is *unpredictable and completely uncontrollable*.

- If I swipe once, the canvas scrolls along with my finger. If I let go and swipe again, the canvas keeps moving on its own, instead of following my finger (which other properly-designed apps do). The second swipe only takes effect after I let go of the screen.
- Sometimes swiping twice causes the app to zoom in/out instead of scrolling twice (followed by some scrolling due to momentum).
- The document zoom sometimes changes randomly.
- I can zoom in so far I get text with letters flickering on top of each other, with toast "Not enough memory for plot visualization".
- Pinch-to-zoom does not zoom around the locations of my 2 fingers. Instead the document scrolls about an unpredictable and uncontrollable point. And the document changes location 1/2 second after I let go of pinch-to-zoom or double-tap zoom.
    - If you pinch in the middle of a text field, it jumps to the "right" location. If your cursor is in a text field but you scroll down then pinch, it jumps from your current location to the text field.
- When I tap in a text field, the keyboard pushes the document around, causing it to move in unpredictable ways. I think it's trying to keep the cursor visible on-screen, and not covered by the keyboad.

**Comment by mkulesh** [comment]
Hi @activedecay, thanks for vote. I implement now some new mathematical functionality, and as the next step I will try to fix this problem.

**Comment by mkulesh** [comment]
Hi @activedecay, @jimbo1qaz 
I improved the behavior of canvas scrolls:
> If I swipe once, the canvas scrolls along with my finger. If I let go and swipe again, the canvas keeps moving on its own, instead of following my finger

Now, this problem is fixed. Please could you test it using the latest autobuild:
https://github.com/mkulesh/microMathematics/raw/autobuild/autobuild/microMathematics-v2.17.4.apk

**Comment by activedecay** [comment]
i most definitely appreciate your fixing that! and so quickly.
however, if you publish to f-droid when you're confident you've worked out the kinks, i'll be happy to test that out for you and report back. cheers mate

**Comment by mkulesh** [comment]
Ok @activedecay, thank you. I'll inform you when new release will be available on F-Droid (appox. the end of the next week)

**Comment by TheOtherDoctor** [comment]
Installed the app today from f-droid, I see essentially all effects as described by the original post. Just scrolling through the "how to use document" ended reproducably in tiny fonts, squeezing the doc width to like 15% of screen width, unreadable. No zooming worked to get it back to readable size. 
Only when turning off "enable zoom" in app settings, the getting started doc became usable.
I cannot tell which version this is as the "(i) about" entry in the main menu seems broken, not showing any info. F-Droid says (and documentation menu entry opens pdf for) 2.19.0; OS is Lineage 14.1.

**Comment by mkulesh** [comment]
Released in version 2.21.0
