### ISSUE TITLE
Implement plus-minus operator

### ISSUE THREAD

**Issue by frozenspider** [mkulesh/microMathematics#84]
Please implement a `±x` function for taking an expression with both positive and negative sign. This is useful e.g. when square roots or absolute values are involved.

Initial text for historical reasons:
~~Please implement a `|x|` function for absolute value of an expression. This is useful e.g. when square roots are involved.~~

**Comment by mkulesh** [comment]
Hi, @frozenspider 
there is already such a function. Please try
a := |-5|
a = ?
b := |1+2i|
b = ?
c := |sin(4)|
c =
Please see attached screenshot
![screenshot_20181224-123436](https://user-images.githubusercontent.com/30557348/50398506-672d4200-0778-11e9-95e9-30187c0f0147.png)
Or do you need an other function?

**Comment by frozenspider** [comment]
Sorry @mkulesh, got a brain fart :) What I've intended to ask for was an exact opposite of that, plus-minus operator `±`.
Corrected the issue.

**Comment by mkulesh** [comment]
Hi @frozenspider 
Just to better understand...
If we have an expresssion with a single ± operator:
a := 1 ± 2
Then the result is an array with two elements, where the first corresponds to 1 + 2, and the second corresponds to 1 - 2.
That is in the case if we have two or more ± operators in the same equation:
a := (1 ± 2)*(3 ± 3)?
Shall the result be an array with 4 elements (that corresponds to 4 different combination) or only 2 elements (for the first element, we use "+" for all ± operators, and for the second we use "-" for all ± operators)?

**Comment by frozenspider** [comment]
I see too ways of resolving this. Either:

* Each ± sign would double the size of possible values
* Use both ± and ∓ do denote two ways of evaluation corresponding to top and bottom parts of the respective signs, i.e. `x := a ± b ∓ c ∓ d` would mean `a + b - c - d` and `a - b + c + d`

As far as I'm aware, second notation is more common, e.g. `cos(x ± y) = cos(x)cos(y) ∓ sin(x)sin(y)`

**Comment by mkulesh** [comment]
The second notation is also easier to implemen. I think I can first implement the second notation (where results always consists of two values):
x := a ± b ∓ c ∓ d would mean a + b - c - d and a - b + c + d
I can start with the implementation in January. Is it ok for you?

**Comment by frozenspider** [comment]
I'm merely a petitioner, I'll be happy with whatever improvement you do :)
Thanks for the great app!

**Comment by mkulesh** [comment]
Currently, no plan to fix it
