### ISSUE TITLE
Addition of permutations and combinations  in micromaths+

### ISSUE THREAD

**Issue by peerzadaaabid** [mkulesh/microMathematics#87]
Of course, during solving the problems in mathematics, a mathematician will certainly come across permutation and combination, but I found these inbuilt functions are missing from this special mathematics software. My suggestion is primarily linked with the development of permutations and combinations in this software.
Thanks 
With regards
Peerzada_aabid

**Comment by mkulesh** [comment]
Hi @peerzadaaabid, thank you for proposal. Unfortunately, I am not too familiar with combinatorics. Could you may be contribute to the project by implementation of these functions?
