### ISSUE TITLE
Support for different base calculation

### ISSUE THREAD

**Issue by iilyak** [mkulesh/microMathematics#89]
I was trying to find how to work with not base-10 numbers and couldn't find any documentation. I need to specify and output numbers in arbitrary (for example 2,10,12,16,60) base. Is it supported as units maybe?

**Comment by Renu-Balhara** [comment]
Do you need a program that takes input number and it's base and display output in any of the arbitrary base (2,10,8 and 16) ?
Working with other bases (like 12,60, etc.) seems more complex.

**Comment by iilyak** [comment]
> Do you need a program that takes input number and it's base and display output in any of the arbitrary base (2,10,8 and 16) ?

In my case I needed bases 12 and 60 as well.

**Comment by Renu-Balhara** [comment]
> > Do you need a program that takes input number and it's base and display output in any of the arbitrary base (2,10,8 and 16) ?
> 
> In my case I needed bases 12 and 60 as well.

Sure, I can add them too. I will be able to provide the program by 7th oct evening, is it fine?

**Comment by iilyak** [comment]
>  Sure, I can add them too. I will be able to provide the program by 7th oct evening, is it fine?

Of cause. Thank you for looking into it.

**Comment by mkulesh** [comment]
Hi @iilyak, 
Sorry for the radio silence for a while, I worked for an other project last time.

I expanded the result properties by radix selection field, see attached screenshot.
The radix can be selected between 2 and 36. If you like to test it, please download and install the latest nightly build from here:
https://github.com/mkulesh/microMathematics/raw/autobuild/autobuild/microMathematics-v2.20.1-debug.apk

![radix](https://user-images.githubusercontent.com/30557348/98299836-9fc71500-1fb8-11eb-90ba-bfdebfd5cf70.png)

**Comment by iilyak** [comment]
Hi @mkulesh, I looked at screenshots it looks good. I was unable to install the apk on my device. It is silently fails to install.

**Comment by mkulesh** [comment]
Hi @iilyak,
this APK was not signed. Depending on Android version you may need to uninstall previously installed signed version in order to install an unsigned. However, I uploaded a new APK that is now signed and can be installed without a problem. Please download again https://github.com/mkulesh/microMathematics/raw/autobuild/autobuild/microMathematics-v2.20.1-release.apk

**Comment by iilyak** [comment]
As you said I need to uninstall previous version (which was installed from F-Droid store).

I cannot figure out how to bring result properties dialog. I tried a long press on the numeric value and it didn't appear.

**Comment by mkulesh** [comment]
Hi @iilyak,
Just select a whole result formula. The simplest way is to long press on "=" sign and use the button "Expand selection" from the top toolbar if whole formula is not yet selected. When the result formula is selected, a new floating button "Property" will appear:
![object_properties](https://user-images.githubusercontent.com/30557348/98729494-4b96a900-239b-11eb-93ba-bf7efb17571a.png)

**Comment by mkulesh** [comment]
Released in version 2.20.1
