### ISSUE TITLE
Missing automatic parentheses around a fraction or when entering its denominator

### ISSUE THREAD

**Issue by mmaxs** [mkulesh/microMathematics#98]
μMath+ v2.20.0.

Two expressions that look the same are evaluated differently:
![IMG_20201107_223430](https://user-images.githubusercontent.com/10092391/98449973-8a352500-2149-11eb-8be2-56b69da939b2.jpg)

The first expression is entered by using the `#•#` template first with a tool button, wherein the left placeholder is filled in with `2/2` keystroke, and the right one with `2`.
The second expression is enered as a straight keystroke `2/2*2`. According to its view on the worksheet  it should be evaluated as = 2. Actualy it is treated as 2/(2*2)=0.5

Here is another example (values with units). Here, `km/hr` is intuitively considered  a unit of measure for `12`, not a specifically entered fraction `12 km / 1 hr`, so the first operand of multiplication is expected to be implicitly enclosed in parentheses.
![IMG_20201107_231210](https://user-images.githubusercontent.com/10092391/98450573-c61eb900-214e-11eb-8ca2-79fcf14b1364.jpg)

---
Thank you for a great app!

---

**Comment by mkulesh** [comment]
Hi @mmaxs 
I fixed the first problem. Now, the parenthesis will be automatically added into the right placeholder. If you like to test it, please install the latest nightly build from here:
https://github.com/mkulesh/microMathematics/raw/autobuild/autobuild/microMathematics-v2.20.1-debug.apk
This build is not signed. Depending on Android version you may need to uninstall the previous signed version.
For the second example (values with units), I need some more time to investigate it.

**Comment by mkulesh** [comment]
Hi @mmaxs,
missing parenthesis before division is now fixed, please install the latest build: https://github.com/mkulesh/microMathematics/raw/autobuild/autobuild/microMathematics-v2.20.1-debug.apk

**Comment by mmaxs** [comment]
Hi, Mikhail. I have been using it with a couple of worksheets for a while and have found no new problems.

**Comment by mkulesh** [comment]
Released in version 2.20.1
